package br.gov.sp.fatec.trampoz_api.resumes;

import br.gov.sp.fatec.trampoz_api.freelancers.FreelancerEntity;
import br.gov.sp.fatec.trampoz_api.shared.AutoGeneratedId;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@Table(name = "res_resume")
@Entity
@AttributeOverride(name = "id", column = @Column(name = "res_id"))
public class ResumeEntity extends AutoGeneratedId {

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fre_id")
    private FreelancerEntity freelancer;

    @Column(name = "res_portfolio_link", columnDefinition = "text")
    private String portfolioLink;

    @Column(name = "res_linkedin_link", columnDefinition = "text")
    private String linkedinLink;

    @Column(name = "res_professional_experience", columnDefinition = "text")
    private String professionalExperience;

    @Column(name = "res_academic_experience", columnDefinition = "text")
    private String academicExperience;

    @Column(name = "res_skills", columnDefinition = "text")
    private String skills;
}
