package br.gov.sp.fatec.trampoz_api.newsletters;

import br.gov.sp.fatec.trampoz_api.shared.AutoGeneratedId;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "new_newsletter")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "new_type")
@AttributeOverride(name = "id", column = @Column(name = "new_id"))
public abstract class NewsletterEntity extends AutoGeneratedId {
    public NewsletterEntity (String domain) {
        this.setDomain(domain);
    }

    @Column(name = "new_domain")
    private String domain;
}
