package br.gov.sp.fatec.trampoz_api.roles;

import br.gov.sp.fatec.trampoz_api.shared.AutoGeneratedId;
import br.gov.sp.fatec.trampoz_api.users.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@Table(name = "rol_role")
@Entity
@AttributeOverride(name = "id", column = @Column(name = "rol_id"))
public class RoleEntity extends AutoGeneratedId {

    public RoleEntity(RolesEnum role) {
        setName(role);
    }

    @Column(name = "rol_name")
    @Enumerated(EnumType.STRING)
    private RolesEnum name;

    @JsonIgnore
    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "roles")
    private Set<UserEntity> users;
}
